# .travis.yml
# Configure Travis CI service for http://github.com/PDAL
sudo: required

dist: trusty

language: cpp

services:
  - docker

env:
  global:
    # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
    # via the "travis encrypt" command using the project repo's public key
    - secure: "gpzSG/qEeU/kmZGKd21u60BSktcbV1EJrV1aeWBnKyJam4ZuUI400vAoJT/nQX9J47dN0oqxvvpqgaIwoJ8BYiq6U6qSq3OMDApRxmLT1leNDZx10rzlK6XLGYeL3CW4OOFdLbG7RFoEWnThB6IjNmtOFFCvxFeuzZAckU9GMWc="

matrix:
  include:
    - env: PDAL_OPTIONAL_COMPONENTS=none USE_CXX=g++
      compiler: gcc
    - env: PDAL_OPTIONAL_COMPONENTS=all USE_CXX=g++
      compiler: gcc
    - env: PDAL_OPTIONAL_COMPONENTS=all USE_CXX=g++5
      compiler: gcc
      addons:
        apt:
            sources:
              - ubuntu-toolchain-r-test
            packages:
              - g++-5
        coverity_scan:
          project:
            name: "PDAL/PDAL"
            description: "C++ library for translating and manipulating point cloud data"
          notification_email: mateusz@loskot.net
          #build_command_prepend: 
          build_command: docker run -v $TRAVIS_BUILD_DIR:/pdal -e CXX="$CXX" -e CC="$CC" -e PDAL_OPTIONAL_COMPONENTS="all" -t pdal/dependencies:latest /bin/sh -c "/pdal/scripts/ci/script.sh"
          branch_pattern: coverity_scan

before_install:
  - docker --version
  - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-
  - if [[ "$USE_CXX" == "g++5" ]]; then sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 20; fi
  - if [[ "$USE_CXX" == "g++5" ]]; then sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 20; fi
  - if [[ "$USE_CXX" == "g++5" ]]; then sudo update-alternatives --config gcc; fi
  - if [[ "$USE_CXX" == "g++5" ]]; then sudo update-alternatives --config g++; fi
  - $CXX --version
  - ./scripts/ci/before_install.sh

script:
    docker run -v $TRAVIS_BUILD_DIR:/pdal -e CXX="$CXX" -e CC="$CC" -e PDAL_OPTIONAL_COMPONENTS="$PDAL_OPTIONAL_COMPONENTS" -t pdal/dependencies:latest /bin/sh -c "/pdal/scripts/ci/script.sh"

after_success:
  - echo "secure travis:" "$TRAVIS_SECURE_ENV_VARS"
  - sh -c 'if test "$TRAVIS_SECURE_ENV_VARS" = "true" -a "$TRAVIS_BRANCH" = "1.3-maintenance" -a "$PDAL_OPTIONAL_COMPONENTS" = "all"; then echo "publish website"; ./scripts/ci/build_docs.sh; ./scripts/ci/add_deploy_key.sh; ./scripts/ci/deploy_website.sh $TRAVIS_BUILD_DIR/doc/build /tmp; fi'

