# .travis.yml
# Configure Travis CI service for http://github.com/PDAL

sudo: required

before_install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-Linux-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b -p $HOME/miniconda
      export PATH="$HOME/miniconda/bin:$PATH"
      hash -r
      conda config --set always_yes yes --set changeps1 no
      conda update -q conda
      conda info -a

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      cat ./scripts/ci/environment.yml
      conda env create -f ./scripts/ci/environment.yml
      source activate pdal

script:
  - ./scripts/ci/script.sh

after_success:
  - echo "secure travis:" "$TRAVIS_SECURE_ENV_VARS"
  - sh -c 'if test "$TRAVIS_SECURE_ENV_VARS" = "true" -a "$TRAVIS_BRANCH" = "1.7-maintenance"; then echo "publish website"; ./scripts/ci/build_docs.sh; ./scripts/ci/add_deploy_key.sh; ./scripts/ci/deploy_website.sh $TRAVIS_BUILD_DIR/doc/build /tmp; fi'

notifications:
  on_success: always
  on_failure: always
  irc: chat.freenode.net#pdal
  slack:
    rooms:
      secure: AjatYRAUpsczjENkpHPFiLLZ/leDlzx4TH+oPQYZCpA4WpJdNRy0IB4oMR2IYiY+qz0nHDbeMTBvF0l8S6NknZAz20f8buf4IkrdXymBQBOTmLHMWbpgHuSCCu7xMwtG6thjMEmBOXm5UgCcdqvlchcaoAUunyprXQWgJwI+tHE=
    on_failure: always
    on_success: change
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/4c7f3edec32936d6a758
